### ISSUE TITLE
May I ask how to use these scripts, double click it can not run

### ISSUE THREAD

**Issue by v522101** [Rodrigo-NH/UE4HmapsGenerator#1]
Do I need to modify some parameters in the script and then double-click to run it, or do I need to run it in UE4.

**Comment by Rodrigo-NH** [comment]
Hi. You don't need UE4 for the main script to work (srtm2heightmap.py) but you need to have Python [https://www.python.org/](url) and GDAL [https://gdal.org/](url) installed. The other scripts need to be executed in a UE4 session as they use commands from the UE4 python API.
