### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by thomas0000000** [Rodrigo-NH/UE4HmapsGenerator#3]
Hey , em sorry that i may annoy u with that . but im not a scripting guy and try to run ur awsome script. but thats where it starts.. in dont know how or where ,could u please help my noobish ass .   I allready tryed to execute it in qgis but it does nothing
i filled the most i could work with but im 100% that not intendet to work like that
[srtm2heightmap.txt](https://github.com/Rodrigo-NH/UE4HmapsGenerator/files/8297910/srtm2heightmap.txt)

**Comment by thomas0000000** [comment]
i mean i have basic unterstanding of things i did a tiny bit of c++ and other things , but gdal and so on , no clue

**Comment by Rodrigo-NH** [comment]
Hi thomas,
Yeah I think it can be run from QGIS theoretically. But once you have gdal and python in the system anyway you should be able to just run the script.
Try searching tutorials about how to have gdal & python correctly set on your computer.
This is old but a good example (search for updated tutorials perhaps) https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows

**Comment by Rodrigo-NH** [comment]
For reference. Recipe get Python and Gdal set in Windows:
https://gist.github.com/Rodrigo-NH/94d1fe07646052ad32133824c85b4221
